[users]

["admin@example.com"]
password = "$2b$12$0tOC0yVH9b5bzPr1GoDW9uMoUMIQ.KU7v9KRBHmlMZRG0ZEP3Yh3q"  # hashed version of "admin123"
role = "admin"

["user@example.com"]
password = "$2b$12$rT7DP1aIt9bmA5US03ZVgOvBaGHNnWk.LuGXmKvXMzv5tMBXL14de"  # hashed version of "user123"
role = "user"
