[db]
db_host = "your-db-host"
db_user = "your-db-user"
db_password = "your-db-password"
db_name = "your-db-name"

[users]
[email@example.com]
password = "admin123"
role = "admin"

[another@email.com]
password = "user123"
role = "user"
