[db]
db_host = "b4j0t8ksvqfb4e6hawxj-mysql.services.clever-cloud.com"
db_name = "b4j0t8ksvqfb4e6hawxj"
db_user = "unmichyijl7pyhqo"
db_password = "user123"
db_port = 3306

[users]

["admin@example.com"]
password = "$2b$12$0tOC0yVH9b5bzPr1GoDW9uMoUMIQ.KU7v9KRBHmlMZRG0ZEP3Yh3q"
role = "admin"

["user@example.com"]
password = "$2b$12$rT7DP1aIt9bmA5US03ZVgOvBaGHNnWk.LuGXmKvXMzv5tMBXL14de"
role = "user"
